name: mda-user-guide
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter_contrib_nbextensions
  - nglview
  - sphinx
  - ipywidgets
  - mdanalysis=0.20.1
  - MDAnalysisTests
  - pip:
    - sphinx_rtd_theme
    - sphinx-sitemap
    - nbsphinx
    - ipython
    - tabulate
